---
galaxy_info:
  author: RaBe IT-Reaktion
  description: Download and install selinux module. Includes the roles
    [radiorabe.common.download_file](https://github.com/radiorabe/ansible-collection-common/tree/main/roles/download_file) and
    [redhat.rhel_system_roles.selinux](https://github.com/linux-system-roles/selinux).
  issue_tracker_url: https://github.com/radiorabe/ansible-collection-common/issues
  license: AGPL-3.0-only
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      version:
        - all
  galaxy_tags:
    - radiorabe
    - foreman
    - common
    - system
    - selinux
dependencies: []
